version: '3.5'

services: 
    migration:
        image: docker.pkg.github.com/yurii-hunter/upsale/upsale:latest
        container_name: migration
        volumes:
            - ~/db:/usr/src/app
        command: python manage.py migrate

    bot-client:
        image: docker.pkg.github.com/yurii-hunter/upsale/upsale:latest
        container_name: bot-client
        hostname: bot-client
        volumes:
            - ~/db:/usr/src/app
        command: python manage.py startbot
        depends_on: 
            - migration
        
    admin:
        image: docker.pkg.github.com/yurii-hunter/upsale/upsale:latest
        container_name: admin
        hostname: admin
        volumes:
            - ~/db:/usr/src/app
        ports:
            - 8000:80
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - migration