name: BUILD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        push: true
        username: ${ GITHUB_ACTOR }
        password: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}
        registry: docker.pkg.github.com
        repository: yurii-hunter/upsale/upsale
        tag_with_ref: true
        add_git_labels: true
        tag_with_sha: true