name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        push: true
        username: _json_key
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: yurii-hunter/upsale/upsale
        tag_with_ref: true
        add_git_labels: true
  deploy:
    runs-on: self-hosted
    steps:
    - name: docker-compose up
      run: docker-compose up -d