name: DEPLOY

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Start App
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u yurii.myslyvets@gmail.com --password-stdin
        docker-compose up -d
