name: DEPLOY_CHERRY

on: registry_package

jobs:
  deploy:
    runs-on: 
      - self-hosted
      - cherry
    env:
      BOT_API_TOKEN: ${{ secrets.BOT_API_TOKEN_CHERRY }}

    steps:
    - name: info
      run: echo ${{ github.event.registry_package.package.name }}
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${ GITHUB_ACTOR }
        password: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}
    - name: stop application
      run: docker-compose down
    - name: migrate database
      run: docker-compose up migration
    - name: start application
      run: docker-compose up -d admin bot-client